// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/event.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	StartAt              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=startAt,proto3" json:"startAt,omitempty"`
	Duration             int64                `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Description          string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	User                 string               `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	NotifyBefore         int64                `protobuf:"varint,7,opt,name=notifyBefore,proto3" json:"notifyBefore,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_d236019f42e23116, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetStartAt() *timestamp.Timestamp {
	if m != nil {
		return m.StartAt
	}
	return nil
}

func (m *Event) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Event) GetNotifyBefore() int64 {
	if m != nil {
		return m.NotifyBefore
	}
	return 0
}

func init() {
	proto.RegisterType((*Event)(nil), "Event")
}

func init() {
	proto.RegisterFile("api/event.proto", fileDescriptor_d236019f42e23116)
}

var fileDescriptor_d236019f42e23116 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x89, 0x6d, 0xba, 0x3a, 0x15, 0x84, 0xe0, 0x21, 0xec, 0xc5, 0xd0, 0xd3, 0x9e, 0xb2,
	0xa0, 0xbe, 0x80, 0x05, 0x5f, 0x60, 0xf1, 0xe4, 0x2d, 0xba, 0xb3, 0x25, 0xd0, 0x6e, 0x42, 0x32,
	0x11, 0x7c, 0x58, 0xdf, 0x45, 0x9c, 0xb8, 0x62, 0x4f, 0xc9, 0xff, 0xcf, 0x3f, 0xf3, 0xfd, 0x70,
	0xe3, 0xa2, 0xef, 0xf1, 0x03, 0x67, 0xb2, 0x31, 0x05, 0x0a, 0xed, 0xdd, 0x21, 0x84, 0xc3, 0x11,
	0x7b, 0x56, 0x6f, 0x65, 0xea, 0xc9, 0x9f, 0x30, 0x93, 0x3b, 0xc5, 0x1a, 0xd8, 0x7d, 0x09, 0x90,
	0xcf, 0x3f, 0x0b, 0x4a, 0xc1, 0xba, 0x14, 0x3f, 0x6a, 0x61, 0x44, 0x77, 0x35, 0xf0, 0x5f, 0xdd,
	0x82, 0x24, 0x4f, 0x47, 0xd4, 0x17, 0x6c, 0x56, 0xa1, 0x1e, 0xa1, 0xc9, 0xe4, 0x12, 0x3d, 0x91,
	0x5e, 0x19, 0xd1, 0x6d, 0xef, 0x5b, 0x5b, 0x31, 0x76, 0xc1, 0xd8, 0x97, 0x05, 0x33, 0x2c, 0x51,
	0xd5, 0xc2, 0xe5, 0x58, 0x92, 0x23, 0x1f, 0x66, 0xbd, 0x36, 0xa2, 0x5b, 0x0d, 0x7f, 0x5a, 0x19,
	0xd8, 0x8e, 0x98, 0xdf, 0x93, 0x8f, 0x3c, 0x96, 0x4c, 0xfb, 0x6f, 0x71, 0xbb, 0x8c, 0x49, 0x6f,
	0x7e, 0xdb, 0x65, 0x4c, 0x6a, 0x07, 0xd7, 0x73, 0x20, 0x3f, 0x7d, 0xee, 0x71, 0x0a, 0x09, 0x75,
	0xc3, 0x57, 0xcf, 0xbc, 0x7d, 0xf3, 0x2a, 0x6b, 0xa9, 0x0d, 0x3f, 0x0f, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x40, 0xfa, 0x87, 0xec, 0x23, 0x01, 0x00, 0x00,
}
